name: C/C++ CI

on: 
 push :
   branches:
    - master
 pull_request:
       
jobs:
  build:

    runs-on: [self-hosted, windows]
    
    steps:
    - uses: actions/checkout@v2    
          
    - name:  Setup MSBuild
      shell: cmd
      run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86
          msbuild transfer-learning.sln /p:Platform="x64";Configuration="Release"
